#!/bin/sh
clear
IP = $1
echo $IP

mkdir /root/logs

cp /var/log/dnsmasq.log.10.gz /root/logs/
cp /var/log/dnsmasq.log.9.gz /root/logs/
cp /var/log/dnsmasq.log.8.gz /root/logs/
cp /var/log/dnsmasq.log.7.gz /root/logs/
cp /var/log/dnsmasq.log.6.gz /root/logs/
cp /var/log/dnsmasq.log.5.gz /root/logs/
cp /var/log/dnsmasq.log.4.gz /root/logs/
cp /var/log/dnsmasq.log.3.gz /root/logs/
cp /var/log/dnsmasq.log.2.gz /root/logs/
cp /var/log/dnsmasq.log.1 /root/logs/
cp /var/log/dnsmasq.log /root/logs/

cd /root/logs

gunzip dnsmasq.log.10.gz
gunzip dnsmasq.log.9.gz
gunzip dnsmasq.log.8.gz
gunzip dnsmasq.log.7.gz
gunzip dnsmasq.log.6.gz
gunzip dnsmasq.log.5.gz
gunzip dnsmasq.log.4.gz
gunzip dnsmasq.log.3.gz
gunzip dnsmasq.log.2.gz

cat dnsmasq.log.10 | grep $IP | grep -v "a.root" > TEMP
cat dnsmasq.log.9 | grep $IP | grep -v "a.root" >> TEMP
cat dnsmasq.log.8 | grep $IP | grep -v "a.root" >> TEMP
cat dnsmasq.log.7 | grep $IP | grep -v "a.root" >> TEMP
cat dnsmasq.log.6 | grep $IP | grep -v "a.root" >> TEMP
cat dnsmasq.log.5 | grep $IP | grep -v "a.root" >> TEMP
cat dnsmasq.log.4 | grep $IP | grep -v "a.root" >> TEMP
cat dnsmasq.log.3 | grep $IP | grep -v "a.root" >> TEMP
cat dnsmasq.log.2 | grep $IP | grep -v "a.root" >> TEMP
cat dnsmasq.log.1 | grep $IP | grep -v "a.root" >> TEMP
cat dnsmasq.log | grep $IP | grep -v "a.root" >> TEMP

sort -b TEMP > TEMP_sort
cat TEMP_sort | grep ".com" > com
cat TEMP_sort | grep "facebook" > facebook
cat TEMP_sort | grep "instagram" > instagram
cat TEMP_sort | grep "twitter" > twitter
cat TEMP_sort | grep "microsoft" > microsoft
cat TEMP_sort | grep "apple\|icloud" > apple
cat TEMP_sort | grep "update" > update
cat TEMP_sort | grep "upgrade" > upgrade
cat TEMP_sort | grep "eset\|avast\|avg\|kaspar" > antivir

for i in $(seq 01 31);
do for j in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23;
do egrep -io "$i $j" TEMP_sort | sort | echo "$i $j:"`wc -l` >> TEMP_dates;
done;
done

clear
echo Cleaning...
rm dnsmasq*.*
echo OK.
